name: Teste unitário e lint

on: push

jobs:
  testando_codigo:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: listar diretorio
        run: ls -la
      - name: obter codigo do do repositorio
        uses: actions/checkout@v3
      - name: instalar node
        run: actions/setup-node@v3
      - name:  instalar dependencias
        run: npm install
      - name: executar testes
        run: npm test
      - name: gerar relatorio
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest 
          reporter: junit
          output-file: junit.xml